newoptims
facebookresearch/nevergrad pull request #1140
Opened 2021-06-10 11:57 UTC by teytaud

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context / Related issue

## How Has This Been Tested (if it applies)

## Checklist

- [x] The documentation is up-to-date with the changes I made.
- [x] I have read the [**CONTRIBUTING**](https://facebookresearch.github.io/nevergrad/contributing.html) document and completed the CLA (see [**CLA**](https://facebookresearch.github.io/nevergrad/contributing.html#contributor-license-agreement-cla)).
- [x] All tests passed, and additional code has been covered with new tests.

2021-06-10 16:08 UTC, teytaud commented
Aaaaaah it does not work for black_box because it is not picklable, and it does not work for rbfopt because it has hidden dependencies to bonmin, which are not installed when you install rbfopt. I see no solution. Grumpf.

2021-06-14 14:28 UTC, jrapin requested changes

2021-06-14 14:28 UTC, jrapin commented on requirements/dev.txt
> +rbfopt>=4.2.2
this does not seem standard, please move this to bench.txt

2021-06-14 14:28 UTC, jrapin commented on nevergrad/optimization/recastlib.py
> +                    best_x = np.arctanh(x)
I would avoid tanh, really, this clips too fast. tan/arctan is better

2021-06-14 14:28 UTC, jrapin commented on nevergrad/optimization/recastlib.py
> +    def local_objective_function(self, x) -> float:
please make this kind of methods private

2022-03-14 06:45 UTC, teytaud commented
It's sad but RBFOPT has no proper way to install its dependencies. This can not work unless some apt-get have been done. 
Maybe I could ensure that this works for users who do have the subdependencies installed, but that makes our code more complicated and difficult to maintain. I prefer to close for now.

2022-03-14 06:45 UTC, closed without merging