Creating a group for decomposition-based methods and adding decomposition-based methods.
facebookresearch/nevergrad pull request #808
Opened 2020-09-04 11:44 UTC by teytaud

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context / Related issue

## How Has This Been Tested (if it applies)

## Checklist

- [x] The documentation is up-to-date with the changes I made.
- [x] I have read the [**CONTRIBUTING**](https://facebookresearch.github.io/nevergrad/contributing.html) document and completed the CLA (see [**CLA**](https://facebookresearch.github.io/nevergrad/contributing.html#contributor-license-agreement-cla)).
- [x] All tests passed, and additional code has been covered with new tests.

2020-10-13 12:43 UTC, jrapin requested changes

2020-10-13 12:43 UTC, jrapin commented on nevergrad/benchmark/optgroups.py
> +    return [optim.name if not isinstance(optim, str) else optim for optim in get_optimizers(*names, seed=seed)]
Why do you use this and not `get_optimizers("splitters")`?
This should *not* be needed because it will not always work.

2020-10-13 12:43 UTC, jrapin commented on nevergrad/optimization/experimentalvariants.py
> +ProgONOPOInf = ConfSplitOptimizer(num_optims=100000, progressive=True, multivariate_optimizer=OptimisticNoisyOnePlusOne).set_name(
You should define this directly in `splitters`, no need to register it
for instance:
```python
def splitters() -> tp.List[Optim]:
    optims: tp.List[Optim] = [x for x in ng.optimizers.registry if "Prog" in x]
    optims.append(ConfSplitOptimizer(num_optims=100000, progressive=True, multivariate_optimizer=OptimisticNoisyOnePlusOne).set_name("ProgONOPOInf"))
    return optims
```

Also, no need to sort the list, this is done by `get_optimizers`

2020-12-06 10:50 UTC, teytaud commented
Rewrittten in 923 and 927.

2020-12-06 10:50 UTC, closed without merging